name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "$EC2_SSH_KEY" > my-ec2-key.pem
        chmod 600 my-ec2-key.pem
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH to EC2 and run commands
      run: |
        ssh -o StrictHostKeyChecking=no -i my-ec2-key.pem ec2-user@3.110.153.44 'echo "Hello from GitHub Actions!" && rinusindhuja && ls -la'
